name: Publish to PyPi

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up git credentials
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Get the version from the tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Update version and commit
        run: |
          sed -i -E 's/version = .*/version = "${{ steps.get_version.outputs.VERSION }}"/' pyproject.toml
          git add pyproject.toml
          git commit -m "Updated version to ${{ steps.get_version.outputs.VERSION }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build package
        uses: abatilo/actions-poetry@v1.11.0
        with:
          python_version: 3.8
          args: build

      - name: Publish to pypi
        uses: pypa/gh-action-pypi-publish@v1.0.0a0
        with:
          password: ${{ secrets.pypi_token }}
